#!/bin/bash

[[ -d /tmp/blog ]] && rm -rf /tmp/blog

cd /tmp
git clone git@github.com:jreisinger/blog.git
cd blog

# Get the last modify time from git and touch all the files with it
# (this is to able to sort blog entries by mtime)
for f in `find publish -type f`; do
    git log -1 --date=iso -- $f | \
    grep ^Date | \
    perl -wnla -e 'print "@F[1,2]"' | \
    perl -wn -s -e 'my @stamp = m{\d\d(\d\d)-(\d\d)-(\d\d) (\d\d):(\d\d):\d\d} ; my $stamp = join "", @stamp ; system "touch -t $stamp $file"' -- -file=$f
done

# Blog entries
rm -rf /var/www/www.openhouse.sk/public/blog/*
cp -pr /tmp/blog/publish/* /var/www/www.openhouse.sk/public/blog/
# iDoneThis
cp /tmp/blog/jozef.md /var/www/www.openhouse.sk/public/

# Clean up
cd /tmp
rm -rf blog
