#!/bin/bash

[[ -d /tmp/blog ]] && rm -rf /tmp/blog

cd /tmp
git clone git@github.com:jreisinger/blog.git

rm /var/www/www.openhouse.sk/public/blog/*
cp /tmp/blog/publish/* /var/www/www.openhouse.sk/public/blog

rm -rf blog
